### ISSUE TITLE
dotnet new new masafx and restore failed

### ISSUE THREAD

**Issue by JaneConan** [masastack/MASA.Templates#2]
Description
通过cli创建masafx后，提示restore失败

Environment
.Net SDK Version:
MASA Framework Version: Masa.Template::0.6.862

Demo
![image](https://user-images.githubusercontent.com/26090153/223676155-0b1f2344-8678-476e-aaa2-99a9ee0c55af.png)

**Comment by JaneConan** [comment]
我们也可以一起参与到 bug fix 的工作中么👀

**Comment by doddgu** [comment]
> 我们也可以一起参与到 bug fix 的工作中么👀

当然，非常欢迎，需要我们提供什么帮助吗？

**Comment by JaneConan** [comment]
> > 我们也可以一起参与到 bug fix 的工作中么👀
> 
> 当然，非常欢迎，需要我们提供什么帮助吗？

目前还好，先跟您们解决这次问题。不过我在用私有化部署MASAStack时，确实您们在很多appsettings.json中，有暴露您们的数据库及缓存链接地址，CDN加速我们在局域网里也用不了，包括我可能没有注意到的细节。这些还要再试着解决掉~

**Comment by doddgu** [comment]
>目前还好，先跟您们解决这次问题。不过我在用私有化部署MASAStack时，确实您们在很多appsettings.json中，有暴露您们的数据库及缓存链接地址，CDN加速我们在局域网里也用不了，包括我可能没有注意到的细节。这些还要再试着解决掉~

我们数据库和缓存地址其实问题不大，我们是环境隔离的。而且后面有时间我们会定义一套新的规则，能够跟helm拉起来的保持一致。
cdn加速局域网不能用的问题也可以提issue，我们后面有空可以考虑提供一个纯离线版本。

**Comment by JaneConan** [comment]
> > 目前还好，先跟您们解决这次问题。不过我在用私有化部署MASAStack时，确实您们在很多appsettings.json中，有暴露您们的数据库及缓存链接地址，CDN加速我们在局域网里也用不了，包括我可能没有注意到的细节。这些还要再试着解决掉~
> 
> 我们数据库和缓存地址其实问题不大，我们是环境隔离的。而且后面有时间我们会定义一套新的规则，能够跟helm拉起来的保持一致。 cdn加速局域网不能用的问题也可以提issue，我们后面有空可以考虑提供一个纯离线版本。

好的 感谢解答，我这边会提issue~ 😊


另外，咱们这个issue，您们看一下nuget的模板描述文件。我发现是sln模板这边的问题，我这边fork然后开一个分支，修改后给您们提pr可以么？
![image](https://user-images.githubusercontent.com/26090153/225498837-1145b05d-bf24-4bdc-9683-00257cb2f27c.png)

**Comment by doddgu** [comment]
@zhenlei520 PTAL

**Comment by zhenlei520** [comment]
很感谢你的反馈，此问题已经在 https://github.com/masastack/MASA.Templates/pull/5 进行修复, 关于Framework Template模版的项目结构在 https://github.com/masastack/MASA.Templates/pull/2 中详细说明

**Comment by zhenlei520** [comment]
如果你有兴趣的话，欢迎一起参与到1.0.0模版的升级改造中来

**Comment by JaneConan** [comment]
> 如果你有兴趣的话，欢迎一起参与到1.0.0模版的升级改造中来

好的 感谢邀请~ 已看到您们的修复，后边我升级模板后，再试试~ 1.0.0的特性，咱们有列出么，我看看自己能够实现哪些~ 👀

**Comment by zhenlei520** [comment]
在新功能上模版暂时并不会有太大的改动，但是目前模版有两个必须要解决的问题:

1. 需要升级依赖Framework版本到1.0.0 (可暂时使用预览版，等正式版发布后调整为正式版)
2. 调整模版的配置参数、创建项目名等，确保开发者不会对此有歧义，比如说: Masa.Framework.Client -> Masa.Framework.BlazorWebAssembly
3. 增加不同功能下文件结构示意图，使得模版项目可以被人更容易理解、也帮助后期定位问题排查问题更加轻松
